version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@timescaledb/mydatabase
      - FLASK_ENV=development
      - FLASK_APP=src
    command: flask run --host=0.0.0.0 --port=5000 --reload
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    restart: unless-stopped

volumes:
  timescaledb_data:
